version: '3.9'

name: funke-wallet-ecosystem
services:
  
  wallet-db:
    image: mariadb
    container_name: wallet-db
    hostname: wallet-db
    restart: on-failure
    ports:
      - 127.0.0.1:3307:3307
    expose: 
      - 3307
    environment:
      MARIADB_HOST: wallet-db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: myuser
      MARIADB_PASSWORD:
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    healthcheck:
      test: ["CMD", "mariadb" ,"-uroot", "-proot", "--protocol=TCP", "-hlocalhost", "--port=3307",  "-estatus"]
      start_period: 60s
      #start_interval: 5s  # Not yet supported it seems, but upcoming: https://github.com/docker/compose/issues/10830
      interval: 5s         # Delete this line when start_interval becomes supported
      timeout: 2s
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./db-setup/scripts/:/docker-entrypoint-initdb.d/

  # wallet-phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: wallet-phpmyadmin
  #   hostname: wallet-phpmyadmin
  #   ports:
  #     - 8081:8081
  #   environment:
  #     APACHE_PORT: 8081
  #     PMA_HOST: wallet-db
  #     PMA_PORT: 3307

  funke-wallet-backend-server:
    container_name: funke-wallet-backend-server
    build:
      context: $PWD/funke-wallet-backend-server
      dockerfile: development.Dockerfile
      secrets:
        - npmrc
    image: funke-wallet-backend-server:dev
    restart: on-failure
    ports:
      - 8002:8002
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - ./funke-wallet-backend-server:/app:rw
      - ./.vscode/:/app/.vscode:rw
      - type: tmpfs
        target: /dist
        tmpfs:
          mode: 01777
    deploy:
      resources:
          limits:
            memory: 1G

  funke-wallet-frontend:
    build:
      context: $PWD/funke-wallet-frontend
      dockerfile: development.Dockerfile
      secrets:
        - npmrc
    image: funke-wallet-frontend:dev
    container_name: funke-wallet-frontend
    hostname: funke-wallet-frontend
    ports:
      - 3000:3000
    volumes:
      - ./funke-wallet-frontend/public:/app/public:rw
      - ./funke-wallet-frontend/src:/app/src:rw
      - ./funke-wallet-frontend/.env:/app/.env:rw
      - ./.vscode/:/app/.vscode:rw
      - type: tmpfs
        target: /app/node_modules/.cache
        tmpfs:
          mode: 01777

  ausweisapp:
    image: governikus/ausweisapp2
    ports:
      - 127.0.0.1:24727:24727

  ausweisapp-client:
    build:
      context: $PWD/ausweissapp-client
      dockerfile: development.Dockerfile
    volumes:
      - ./ausweissapp-client:/app
    depends_on:
      - ausweisapp

  apache-proxy:
    build:
      context: $PWD/apache-proxy
      dockerfile: Dockerfile.apache-rproxy
    restart: always
    ports:
      - 80:80
      - 443:443

volumes:
  datadir:
  cache:
    driver: local

secrets:
  npmrc:
    file: ./.npmrc
